services:
  api:
    build:
      context: ./src
      dockerfile: Dockerfile.Api
    environment:
      BURSTCHAT_API_HOST: localhost
      BURSTCHAT_API_PORT: 5000
    ports:
    - 5000:5000
    profiles:
    - backend
    - debug

  signal:
    build:
      context: ./src
      dockerfile: Dockerfile.Signal
    environment:
      BURSTCHAT_API_HOST: localhost
      BURSTCHAT_API_PORT: 5001
    ports:
    - 5001:5001
    profiles:
    - backend
    - debug

  identity:
    build:
      context: ./src
      dockerfile: Dockerfile.IdentityServer
    environment:
      BURSTCHAT_API_HOST: localhost
      BURSTCHAT_API_PORT: 5002
    ports:
    - 5002:5002
    profiles:
    - backend
    - debug

  client:
    build:
      context: ./src
      dockerfile: Dockerfile.Client
    ports:
    - 4200:4200
    profiles:
    - frontend
    - debug

  database:
    image: postgres:16-bullseye
    restart: always
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: burstchat
    ports:
    - 5433:5433
    volumes:
    - db:/var/lib/postgres/data
    profiles:
    - backend
    - database
    - debug

  identity-database:
    image: postgres:16-bullseye
    restart: always
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: burstchat_identity
    ports:
    - 5434:5434
    volumes:
    - db:/var/lib/postgres/data
    profiles:
    - backend
    - database
    - debug

  asterisk-database:
    image: postgres:16-bullseye
    restart: always
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: burstchat_asterisk
    ports:
    - 5435:5435
    volumes:
    - db:/var/lib/postgres/data
    profiles:
    - backend
    - database
    - debug

volumes:
  db:
    driver: local
