import { Injectable } from '@angular/core';
import { HttpInterceptor, HttpRequest, HttpHandler } from '@angular/common/http';
import { environment } from 'src/environments/environment';

/**
 * This class represents an angular http interceptor service that will identify the url of a request
 * and assign the proper base url.
 * @export
 * @class UrlInterceptorService
 */
@Injectable()
export class UrlInterceptorService implements HttpInterceptor {

    /**
     * This method is executed in order to assign the proper base url to a http request.
     * @param {HttpRequest<any>} request The http request.
     * @param {HttpHandler} next The next interceptor to be executed.
     * @returns An observable generated by the next interceptor.
     * @memberof UrlInterceptorService
     */
    public intercept(request: HttpRequest<any>, next: HttpHandler) {
        const isApi = request.url.startsWith('/api') || request.url.startsWith('api');
        const isIdentity = request.url.startsWith('/connect') || request.url.startsWith('connect');
        let clone = request;

        if (isApi) {
            clone = request.clone({
                url: `${environment.apiUrl}${request.url}`
            });
        }

        if (isIdentity) {
            clone = request.clone({
                url: `${environment.identityUrl}${request.url}`
            });
        }

        return next.handle(clone);
    }

}
